import type { Metadata } from "next";
import Provider from "@/src/components/providers"
// @ts-ignore: side-effect CSS import
import "./globals.css";

export const metadata: Metadata = {
  title: "own-adusa",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <Provider>
        {children}
        </Provider>
        </body>
    </html>
  );
}
